// Code generated by MockGen. DO NOT EDIT.
// Source: source_definition.go
//
// Generated by this command:
//
//	mockgen -source=source_definition.go -destination=../../testhelper/mock/source_definition.go -package=mock_test ISource
//

// Package mock_test is a generated GoMock package.
package mock_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISource is a mock of ISource interface.
type MockISource[Index any, Options any] struct {
	ctrl     *gomock.Controller
	recorder *MockISourceMockRecorder[Index, Options]
}

// MockISourceMockRecorder is the mock recorder for MockISource.
type MockISourceMockRecorder[Index any, Options any] struct {
	mock *MockISource[Index, Options]
}

// NewMockISource creates a new mock instance.
func NewMockISource[Index any, Options any](ctrl *gomock.Controller) *MockISource[Index, Options] {
	mock := &MockISource[Index, Options]{ctrl: ctrl}
	mock.recorder = &MockISourceMockRecorder[Index, Options]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISource[Index, Options]) EXPECT() *MockISourceMockRecorder[Index, Options] {
	return m.recorder
}

// GetIndexes mocks base method.
func (m *MockISource[Index, Options]) GetIndexes(ctx context.Context) ([]Index, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexes", ctx)
	ret0, _ := ret[0].([]Index)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexes indicates an expected call of GetIndexes.
func (mr *MockISourceMockRecorder[Index, Options]) GetIndexes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexes", reflect.TypeOf((*MockISource[Index, Options])(nil).GetIndexes), ctx)
}

// Init mocks base method.
func (m *MockISource[Index, Options]) Init(opts *Options) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockISourceMockRecorder[Index, Options]) Init(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockISource[Index, Options])(nil).Init), opts)
}

// StreamData mocks base method.
func (m *MockISource[Index, Options]) StreamData(arg0 context.Context, arg1 chan map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamData indicates an expected call of StreamData.
func (mr *MockISourceMockRecorder[Index, Options]) StreamData(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamData", reflect.TypeOf((*MockISource[Index, Options])(nil).StreamData), arg0, arg1)
}
